apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-west1
  name: teams-view
  namespace: '872262476135'
spec:
  template:
    spec:
      containerConcurrency: 80
      containers:
      - image: us-west1-docker.pkg.dev/teams-view/container/teams-view@sha256:17611ad39efa58588653511ae9a973bbf966e8a663e629bea0b62d548083ff5b
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: teams-view@teams-view.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
